CREATE DATABASE TaskenSQL;
USE TaskenSQL;
CREATE TABLE CLIENTES (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL
);

CREATE TABLE TELEFONES (
    CPF_CLIENTE VARCHAR(11),
    DDD CHAR(2) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    PRIMARY KEY (CPF_CLIENTE),
    FOREIGN KEY (CPF_CLIENTE)
        REFERENCES CLIENTES(CPF)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
